version: '3.9'
services:
  registry-mysql:
    image: mysql:8
    networks:
      - graphql-federation-network
    container_name: registry-mysql
    restart: on-failure
    volumes:
      - ./mysql-data:/var/lib/mysqlq
    environment:
      MYSQL_ROOT_PASSWORD: GqL456kp7f
      MYSQL_DATABASE: schema-registry
  registry-redis:
    image: redis:6
    networks:
      - graphql-federation-network
    container_name: registry-redis
    restart: on-failure
  schema-registry:
    image: pipedrive/graphql-schema-registry:latest
    networks:
      - graphql-federation-network
    container_name: schema-registry
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      DB_HOST: registry-mysql
      DB_USERNAME: root
      DB_SECRET: GqL456kp7f
      DB_NAME: schema-registry
      REDIS_HOST: registry-redis
      ASSETS_URL: "."
  graphql-gateway:
    image: node:14-alpine
    networks:
      - graphql-federation-network
    container_name: graphql-gateway
    command: "node /app/index.js"
    restart: on-failure
    ports:
      - "6100:3000"
    environment:
      SCHEMA_REGISTRY_URL: "http://schema-registry:3000"
    volumes:
      - ./graphql-gateway:/app

networks:
  graphql-federation-network:
    name: graphql-federation-network
    driver: bridge
