version: '3.9'
services:
  fed-service-a:
    image: node:14-alpine
    networks:
      - federated-services-network
    container_name: fed-service-a
    command: "node /app/index.js"
    restart: on-failure
    ports:
      - "6101:3000"
    environment:
      SCHEMA_REGISTRY_URL: "http://schema-registry:3000"
      SERVICE_NAME: "service_a"
      SERVICE_HOST: "http://fed-service-a"
    volumes:
      - ./service-a:/app
  fed-service-b:
    image: node:14-alpine
    networks:
      - federated-services-network
    container_name: fed-service-b
    command: "node /app/index.js"
    restart: on-failure
    ports:
      - "6102:3000"
    environment:
      SCHEMA_REGISTRY_URL: "http://schema-registry:3000"
      SERVICE_NAME: "service_b"
      SERVICE_HOST: "http://fed-service-b"
    volumes:
      - ./service-b:/app

networks:
  federated-services-network:
    external:
      name: graphql-federation-network
